/* ***********************
* Following MVVM structure
* Entity Class
* *********************** */

package com.example.noteapplication.Model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity (tableName = "note-table")
class Note(val title: String, val description: String) {

    // id for table auto generated by database
    @PrimaryKey(autoGenerate = true)
    var id = 0

}